module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module Indexing
        class FieldReferenceSupertype < ::ElasticGraph::SchemaDefinition::Indexing::FieldReference
          def initialize: (::ElasticGraph::SchemaDefinition::Indexing::FieldReference) -> void
        end

        class FieldReference < FieldReferenceSupertype
          attr_reader json_schema_layers: ::ElasticGraph::SchemaDefinition::jsonSchemaLayersArray
          attr_reader json_schema_customizations: ::Hash[::Symbol, untyped]
          attr_reader doc_comment: ::String?

          def initialize: (
            ::ElasticGraph::SchemaDefinition::Indexing::FieldReference field_reference,
            json_schema_layers: ::ElasticGraph::SchemaDefinition::jsonSchemaLayersArray,
            json_schema_customizations: ::Hash[::Symbol, untyped],
            doc_comment: ::String?
          ) -> void

          def resolve: () -> Field?
          def ==: (untyped other) -> bool
          def eql?: (untyped other) -> bool
          def hash: () -> ::Integer
          def __getobj__: () -> ::ElasticGraph::SchemaDefinition::Indexing::FieldReference
        end
      end
    end
  end
end
