module ElasticGraph
  class Indexer
    class ConfigSupertype
      extend Support::Config::ClassMethods[Config]

      attr_reader latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer]
      attr_reader skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]
      attr_reader indexing_event_decoder: SchemaArtifacts::RuntimeMetadata::Extension

      def initialize: (
        ?latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
        ?indexing_event_decoder: ::Hash[::String, untyped]) -> void

      def with: (
        ?latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
        ?indexing_event_decoder: SchemaArtifacts::RuntimeMetadata::Extension) -> Config

      def self.members: () -> ::Array[::Symbol]
    end

    class Config < ConfigSupertype
      DEFAULT_INDEXING_EVENT_DECODER: ::Hash[::String, untyped]

      private

      def convert_values: (
        latency_slo_thresholds_by_timestamp_in_ms: untyped,
        skip_derived_indexing_type_updates: untyped,
        indexing_event_decoder: untyped
      ) -> ::Hash[::Symbol, untyped]

      def load_indexing_event_decoder: (::Hash[::String, untyped]) -> SchemaArtifacts::RuntimeMetadata::Extension
    end
  end
end
