module ElasticGraph
  class Indexer
    type eventIDString = ::String

    class EventID
      attr_reader type: ::Object?
      attr_reader id: ::Object?
      attr_reader version: ::Object?

      def initialize: (type: ::Object?, id: ::Object?, version: ::Object?) -> void
      def self.new:
        (type: ::Object?, id: ::Object?, version: ::Object?) -> EventID
        | (::Object?, ::Object?, ::Object?) -> EventID
      def self.from_event: (anyEvent) -> EventID
    end
  end
end
