module ElasticGraph
  class Indexer
    class Event < ::Data
      attr_reader op: untyped
      attr_reader type: untyped
      attr_reader id: untyped
      attr_reader version: untyped
      attr_reader record: untyped
      attr_reader ingestion_format: untyped
      attr_reader message_id: untyped
      attr_reader latency_timestamps: untyped
      attr_reader source: untyped

      def initialize: (
        op: untyped,
        type: untyped,
        id: untyped,
        version: untyped,
        record: untyped,
        ?ingestion_format: untyped,
        ?message_id: untyped,
        ?latency_timestamps: untyped,
        ?source: untyped
      ) -> void
      def self.new: (
        op: untyped,
        type: untyped,
        id: untyped,
        version: untyped,
        record: untyped,
        ?ingestion_format: untyped,
        ?message_id: untyped,
        ?latency_timestamps: untyped,
        ?source: untyped
      ) -> instance
      def self.members: () -> ::Array[::Symbol]

      def self.from_hash: (::Hash[::String, untyped]) -> Event

      def with: (**untyped) -> Event
      def to_h: () -> ::Hash[::String, untyped]
    end
  end
end
