module ElasticGraph
  class Indexer
    class FailedEventError < Errors::Error
      extend ::Forwardable
      include _IndexingFailure

      attr_reader main_message: ::String
      attr_reader event: event
      attr_reader event_id: EventID
      attr_reader operations: ::Set[operation]
      attr_reader versioned_operations: ::Array[operation]
      attr_reader id: ::String
      attr_reader full_id: ::String
      attr_reader op: ::String
      attr_reader type: ::String
      attr_reader version: ::Integer
      attr_reader record: untyped

      def self.from_failed_operation_result: (
        Operation::Result,
        ::Set[operation]
      ) -> FailedEventError

      def initialize: (
        event: event,
        operations: ::Set[operation],
        main_message: ::String
      ) -> void
    end
  end
end
