module ElasticGraph
  class Indexer
    class IndexingFailuresError < Errors::Error
      def self.for: (
        failures: ::Array[Indexer::FailedEventError],
        events: ::Array[event]
      ) -> IndexingFailuresError
    end
  end
end
