module ElasticGraph
  class Indexer
    class MalformedEventError < Errors::Error
      include _IndexingFailure

      @message_id: ::String?

      attr_reader payload: untyped
      attr_reader event_id: ::String
      attr_reader main_message: ::String
      attr_reader full_id: ::String

      def initialize: (
        payload: untyped,
        event_id: ::String,
        message_id: ::String?,
        main_message: ::String
      ) -> void
    end
  end
end
