module ElasticGraph
  class Indexer
    interface _RecordPreparer
      def prepare_for_index: [T < ::Object] (::String, T, ::Hash[::String, untyped]) -> T
    end

    class RecordPreparer
      type fieldsByNameHash = ::Hash[::String, FieldMetadata]
      type fieldsByNameByTypeHash = ::Hash[::String, fieldsByNameHash]

      include _RecordPreparer

      module Identity
        extend _RecordPreparer
      end

      def initialize: (
         ::Hash[::String, SchemaArtifacts::RuntimeMetadata::extensionClass?],
         ::Array[TypeMetadata]
      ) -> void

      @indexing_preparer_by_scalar_type_name: ::Hash[::String, SchemaArtifacts::RuntimeMetadata::extensionClass?]
      @fields_by_name_by_concrete_type: fieldsByNameByTypeHash

      class FieldMetadata
        attr_reader type: ::String
        attr_reader name_in_index: ::String

        def initialize: (
          type: ::String,
          name_in_index: ::String
        ) -> void

        def with: (
          ?type: ::String,
          ?name_in_index: ::String
        ) -> FieldMetadata
      end

      class TypeMetadata
        attr_reader name: ::String
        attr_reader fields_by_name: fieldsByNameHash

        def initialize: (
          name: ::String,
          fields_by_name: fieldsByNameHash
        ) -> void

        def with: (
          ?name: ::String,
          ?fields_by_name: fieldsByNameHash
        ) -> TypeMetadata
      end
    end
  end
end
