module ElasticGraph
  class GraphQL
    class DatastoreQuery
      class RoutingPicker
        def initialize: (
          filter_node_interpreter: Filtering::FilterNodeInterpreter,
          schema_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames
        ) -> void

        def extract_eligible_routing_values: (
          ::Array[::Hash[::String, untyped]],
          ::Array[::String]
        ) -> ::Array[routingValue]?

        private

        @filter_value_set_extractor: Filtering::FilterValueSetExtractor[EqualityValueSet]
      end

      type routingValue = untyped
    end
  end
end
