version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: bundler
    directory: /
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      # 1 PR for every single dependency is overkill (it's tedious to have to wade through 20 dependabot PRs!).
      # However, for certain key dependencies that are important or have had a history of initially failing the
      # build on upgrade, we want to keep them in their own PRs. We've listed them in `exclude_patterns` below.
      most-gems:
        patterns: ["*"]
        exclude-patterns:
          - "elasticsearch" # listed here as gem releases align with releases of Elasticsearch itself, and a PR notifies us of it
          - "graphql"
          - "json_schemer"
          - "rack"
          - "rbs"
          - "standard"
          - "steep"

  - package-ecosystem: bundler
    directory: /config/release
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      release-gems:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /config/site
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /elasticgraph-apollo/apollo_tests_implementation
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      apollo-docker:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/elasticsearch
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      elasticsearch-docker:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/opensearch
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      opensearch-docker:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /ai_tools/elasticgraph-mcp-server
    allow:
      - dependency-type: "all" # Allow both direct and transitive updates for all packages.
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      pip:
        patterns: ["*"]
