version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /config/release
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /config/site
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-admin
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-admin_lambda
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-apollo
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-apollo/apollo_tests_implementation
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-apollo/apollo_tests_implementation
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-datastore_core
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-elasticsearch
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-graphql
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-graphql_lambda
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-health_check
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-indexer
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-indexer_autoscaler_lambda
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-indexer_lambda
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-json_schema
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-lambda_support
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-local
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/elasticsearch
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/opensearch
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-opensearch
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-query_interceptor
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-query_registry
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-rack
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-schema_artifacts
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-schema_definition
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph-support
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /elasticgraph
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /ai_tools/elasticgraph-mcp-server
    schedule:
      interval: weekly
