version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /config/release
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /config/site
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-apollo/apollo_tests_implementation
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/elasticsearch
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /elasticgraph-local/lib/elastic_graph/local/opensearch
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /ai_tools/elasticgraph-mcp-server
    schedule:
      interval: weekly
