ruby_version: 3.2
format: progress
ignore:
  - adr/**/*
  - bin/**/*
  - bundle/**/*
  - .bundle/**/*
  - log/**/*
  - tmp/**/*
  - "*/vendor/**/*"
  - "elasticgraph/lib/elastic_graph/project_template/**/*":
    # We don't want the standard comment header to be required on project template files,
    # as they don't need to be on the end files of an ElasticGraph project.
    - ElasticGraph/RequireStandardCommentHeader
  - "config/site/examples/music/schema/artists.rb":
    # This file is a symlink of the `artists.rb` file from the project template, and we can't include the
    # standard header in it without adding it to the project template, which we don't want to do.
    - ElasticGraph/RequireStandardCommentHeader
  - "config/site/examples/music_simplified/schema.rb":
    # This file is rendered at the website, and we don't want to require the standard header on it.
    - ElasticGraph/RequireStandardCommentHeader
  - "**/*.rb":
    # This cop forces syntax that steep does not yet support. (e.g. `def foo(**); bar(**); end`)
    # Once steep supports that, we can stop ignoring this one.
    - Style/ArgumentsForwarding
    # This cop forces syntax that steep does not yet support. (e.g. bare `super` which implicitly forwards args)
    # Once steep supports that, we can stop ignoring this one.
    - Style/SuperArguments

extend_config:
  - config/linting/custom.yaml
