module ElasticGraph
  class Admin
    type indexDefinitionConfigurator = IndexDefinitionConfigurator::ForIndex | IndexDefinitionConfigurator::ForIndexTemplate

    module IndexDefinitionConfigurator
      def self.new: (
        DatastoreCore::client,
        DatastoreCore::indexDefinition,
        ::Hash[::String, untyped],
        io,
        singleton(::Time)
      ) -> indexDefinitionConfigurator
    end
  end
end
