module ElasticGraph
  module SchemaDefinition
    module SchemaElements
      class EnumsForRootDocumentTypes
        def initialize: (State) -> void
        def sort_order_enum_for: (Mixins::_FilterableAndAggregatableType) -> EnumType?
      end
    end
  end
end
