module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module FactoryExtension: ::ElasticGraph::SchemaDefinition::Factory
        BUILT_IN_SCALAR_JSON_SCHEMA_OPTIONS_BY_NAME: ::Hash[::String, ::Hash[::Symbol, untyped]]

        def new_enum_type: (::String) ?{ (::ElasticGraph::SchemaDefinition::SchemaElements::EnumType & SchemaElements::EnumTypeExtension) -> void } -> (::ElasticGraph::SchemaDefinition::SchemaElements::EnumType & SchemaElements::EnumTypeExtension)
        def new_enum_indexing_field_type: (::Array[::String]) -> Indexing::FieldType::Enum
        def new_field: (**untyped) ?{ (::ElasticGraph::SchemaDefinition::SchemaElements::Field & SchemaElements::FieldExtension) -> void } -> (::ElasticGraph::SchemaDefinition::SchemaElements::Field & SchemaElements::FieldExtension)
        def new_index: (::String, ::Hash[::String, untyped], ::ElasticGraph::SchemaDefinition::indexableType) ?{ (::ElasticGraph::SchemaDefinition::Indexing::Index & Indexing::IndexExtension) -> void } -> (::ElasticGraph::SchemaDefinition::Indexing::Index & Indexing::IndexExtension)
        def new_object_indexing_field_type: (
          type_name: ::String,
          subfields: ::Array[Indexing::Field],
          mapping_options: ::ElasticGraph::SchemaDefinition::Mixins::HasTypeInfo::optionsHash,
          doc_comment: ::String?,
          json_schema_options: ::Hash[::Symbol, untyped]
        ) -> Indexing::FieldType::Object
        def new_scalar_type: (::String) ?{ (::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType & SchemaElements::ScalarTypeExtension) -> void } -> (::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType & SchemaElements::ScalarTypeExtension)
        def new_scalar_indexing_field_type: (scalar_type: ::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType) -> Indexing::FieldType::Scalar
        def new_type_with_subfields: (
          ::ElasticGraph::SchemaDefinition::SchemaElements::schemaKind,
          ::String,
          wrapping_type: ::ElasticGraph::SchemaDefinition::SchemaElements::anyObjectType,
          field_factory: ::Method
        ) ?{ (::ElasticGraph::SchemaDefinition::SchemaElements::TypeWithSubfields & SchemaElements::TypeWithSubfieldsExtension) -> void } -> (::ElasticGraph::SchemaDefinition::SchemaElements::TypeWithSubfields & SchemaElements::TypeWithSubfieldsExtension)
        def new_union_indexing_field_type: (::Hash[::String, Indexing::FieldType::Object]) -> Indexing::FieldType::Union
        def new_results: () -> ::ElasticGraph::SchemaDefinition::Results
        def new_schema_artifact_manager: (**untyped) -> ::ElasticGraph::SchemaDefinition::SchemaArtifactManager
      end
    end
  end
end
