module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      class JSONSchemaMergeReporter
        def initialize: (io) -> void

        def report_errors: (::Array[Indexing::JSONSchemaWithMetadata]) -> void
        def report_warnings: (::Set[::ElasticGraph::JSONIngestion::SchemaDefinition::DeprecatedElement]) -> void

        private

        @output: io

        def format_deprecated_elements: (::Enumerable[::ElasticGraph::JSONIngestion::SchemaDefinition::DeprecatedElement]) -> ::String
        def missing_field_error_for: (::String, ::Array[::Integer]) -> ::String
        def missing_type_error_for: (::String, ::Array[::Integer]) -> ::String
        def missing_necessary_field_error_for: (Indexing::JSONSchemaWithMetadata::MissingNecessaryField, ::Array[::Integer]) -> ::String
        def describe_json_schema_versions: (::Array[::Integer], ::String) -> ::String
        def old_versions: (::Array[::Integer]) -> ::String
        def files_noun_phrase: (::Array[::Integer]) -> ::String
      end
    end
  end
end
