module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module SchemaArtifactManagerExtension : ::ElasticGraph::SchemaDefinition::SchemaArtifactManager
        private

        @json_ingestion_json_schemas_artifact: ::ElasticGraph::SchemaDefinition::SchemaArtifact[::Hash[::String, untyped]]?
        @json_ingestion_json_schema_merge_reporter: JSONSchemaMergeReporter?

        def json_ingestion_schema_definition_results: () -> (::ElasticGraph::SchemaDefinition::Results & ResultsExtension)
        def json_ingestion_state: () -> JSONIngestionState
        def artifacts_from_schema_def: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaArtifact[untyped]]
        def json_ingestion_json_schemas_artifact: () -> ::ElasticGraph::SchemaDefinition::SchemaArtifact[::Hash[::String, untyped]]
        def json_ingestion_check_if_needs_json_schema_version_bump: () { (::Integer) -> void } -> void
        def json_ingestion_build_desired_versioned_json_schemas: (::Hash[::String, untyped]) -> ::Hash[::Integer, ::Hash[::String, untyped]]
        def json_ingestion_json_schema_merge_reporter: () -> JSONSchemaMergeReporter
        def json_ingestion_new_versioned_json_schema_artifact: (::Hash[::String, untyped]) -> ::ElasticGraph::SchemaDefinition::SchemaArtifact[::Hash[::String, untyped]]
      end
    end
  end
end
