module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module Indexing
        module FieldType
          class Enum
            include _EnumFieldType
            include EnumExtension

            @field_type: ::ElasticGraph::SchemaDefinition::Indexing::FieldType::Enum

            def self.wrap: (::ElasticGraph::SchemaDefinition::Indexing::FieldType::Enum) -> Enum
            def initialize: (::ElasticGraph::SchemaDefinition::Indexing::FieldType::Enum) -> void
            def to_mapping: () -> ::Hash[::String, untyped]
          end
        end
      end
    end
  end
end
