module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module Indexing
        module FieldType
          module ScalarExtension: ::ElasticGraph::SchemaDefinition::Indexing::FieldType::Scalar
            include _JSONFieldType
          end
        end
      end
    end
  end
end
