module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module Indexing
        module FieldType
          class ScalarSupertype < ::ElasticGraph::SchemaDefinition::Indexing::FieldType::Scalar
            def initialize: (::ElasticGraph::SchemaDefinition::Indexing::FieldType::Scalar) -> void
          end

          class Scalar < ScalarSupertype
            include ValueSemantics

            def json_schema_field_metadata_by_field_name: () -> ::Hash[::String, JSONSchemaFieldMetadata]
            def format_field_json_schema_customizations: (::Hash[::String, untyped]) -> ::Hash[::String, untyped]
            def to_json_schema: () -> ::Hash[::String, untyped]
            def __getobj__: () -> ::ElasticGraph::SchemaDefinition::Indexing::FieldType::Scalar
          end
        end
      end
    end
  end
end
