module ElasticGraph
  module SchemaArtifacts
    module RuntimeMetadata
      class ComponentExtensionSupertype
        attr_reader extension_ref: extensionRef

        def initialize: (
          extension_ref: extensionRef
        ) -> void

        def with: (
          ?extension_ref: extensionRef
        ) -> instance

        def self.new:
          (extension_ref: extensionRef) -> instance
          | (extensionRef) -> instance
      end

      class ComponentExtension < ComponentExtensionSupertype
        self.@loader: ExtensionLoader?
        def self.loader: () -> ExtensionLoader

        EXTENSION_REF: "extension_ref"

        def load_extension: () -> Extension
        def self.from_hash: (::Hash[::String, untyped]) -> ComponentExtension
        def to_dumpable_hash: () -> ::Hash[::String, untyped]
      end
    end
  end
end
