module ElasticGraph
  module SchemaArtifacts
    module RuntimeMetadata
      class ExtensionLoader
        def self.load_component_extensions: (::Array[::Hash[::String, untyped]]) -> ::Array[::Module]
        def initialize: (extensionClass) -> void

        def load: (::String, from: ::String, config: ::Hash[::Symbol | ::String, untyped]) -> Extension

        private

        @interface_def: extensionClass
        @loaded_by_name: ::Hash[::String, Extension]

        def load_extension: (::String, ::String) -> Extension
      end
    end
  end
end
