module ElasticGraph
  module SchemaArtifacts
    module RuntimeMetadata
      class GraphQLFieldSupertype
        attr_reader name_in_index: ::String?
        attr_reader relation: Relation?
        attr_reader computation_function: ::Symbol?
        attr_reader resolver: ConfiguredGraphQLResolver?

        def initialize: (
          name_in_index: ::String?,
          relation: Relation?,
          computation_function: ::Symbol?,
          resolver: ConfiguredGraphQLResolver?
        ) -> void

        def with: (
          ?name_in_index: ::String?,
          ?relation: Relation?,
          ?computation_function: ::Symbol?,
          ?resolver: ConfiguredGraphQLResolver?
        ) -> instance

        def self.new:
          (name_in_index: ::String?, relation: Relation?, computation_function: ::Symbol?, resolver: ConfiguredGraphQLResolver?) -> instance
          | (::String?, Relation?, ::Symbol?, ConfiguredGraphQLResolver?) -> instance
      end

      class GraphQLField < GraphQLFieldSupertype
        EMPTY: GraphQLField
        NAME_IN_INDEX: "name_in_index"
        RELATION: "relation"
        COMPUTATION_FUNCTION: "computation_function"
        RESOLVER: "resolver"

        def self.from_hash: (::Hash[::String, untyped]) -> GraphQLField
        def to_dumpable_hash: () -> ::Hash[::String, untyped]
        def needed?: (::String) -> bool
      end
    end
  end
end
