module ElasticGraph
  module ProtoIngestion
    PROTO_SCHEMA_FILE: ::String
    PROTO_FIELD_NUMBERS_FILE: ::String
    DEFAULT_SCALARS_BY_PROTO_TYPE: ::Hash[::String, ::String]
    VALIDATED_SCALARS: ::Array[::String]
  end
end
