# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

require "elastic_graph/proto_ingestion"
require "elastic_graph/proto_ingestion/indexing_event_decoder"
require "elastic_graph/proto_ingestion/schema_definition/api_extension"
require "elastic_graph/schema_artifacts/from_disk"
require "elastic_graph/schema_definition/rake_tasks"
require "elastic_graph/spec_support/compiled_proto_support"
require "yaml"

module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      RSpec.describe "Protobuf RakeTasks", :rake_task, :in_temp_dir do
        include CompiledProtoSupport

        describe "schema_artifacts:dump" do
          it "loads the dumped runtime metadata and decodes records using the compiled public contract" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID!"
                t.field "displayName", "String", name_in_index: "private_name"
                t.index "products"
              end
            EOS
            run_rake_with_proto("schema_artifacts:dump")
            artifacts = SchemaArtifacts::FromDisk.new("config/schema/artifacts")
            expect(artifacts.available_json_schema_versions).to be_empty
            compile_proto_files("config/schema/artifacts") do |pool, path|
              decoder = IndexingEventDecoder.new(config: {"descriptor_set_file" => path, "format" => "raw"}, schema_artifacts: artifacts, logger: Logger.new(StringIO.new))
              product = pool.lookup("elasticgraph.Product").msgclass
              event = decoder.decode_with_metadata(product.encode(product.new(displayName: "from disk")),
                metadata: {"eg_op" => "upsert", "eg_type" => "Product", "eg_id" => "p1", "eg_version" => "1"}).fetch(0)
              adapter = IngestionAdapter.new(schema_artifacts: artifacts, logger: Logger.new(StringIO.new))
              result = adapter.validate_event(event)
              expect(result.failure).to be_nil
              expect(result.record_preparer.prepare_for_index("Product", result.event.fetch("record"), nil))
                .to eq("id" => "p1", "private_name" => "from disk")
            end
          end

          it "dumps proto artifact when indexed types are defined" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.field "name", "String"
                t.index "products"
              end
            EOS

            expect {
              output = run_rake_with_proto("schema_artifacts:dump")
              expect(output.lines).to include(a_string_including("Dumped", PROTO_SCHEMA_FILE))
            }.to change { read_artifact(PROTO_SCHEMA_FILE) }
              .from(nil)
              .to(
                start_with(
                  "// Generated by `bundle exec rake schema_artifacts:dump`.\n" \
                  "// DO NOT EDIT BY HAND. Any edits will be lost the next time the rake task is run.\n"
                ).and(a_string_including('syntax = "proto3";', "message Product", "string name = 2;"))
              )
          end

          it "idempotently dumps proto artifacts" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.index "products"
              end
            EOS

            run_rake_with_proto("schema_artifacts:dump")

            expect {
              output = run_rake_with_proto("schema_artifacts:dump")
              expect(output.lines).to include(a_string_including("already up to date", PROTO_SCHEMA_FILE))
            }.to maintain { read_artifact(PROTO_SCHEMA_FILE) }.and maintain { read_proto_field_numbers }
          end

          it "persists proto field-number mappings and reuses them on the next dump" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.field "name", "String"
                t.index "products"
              end
            EOS

            expect {
              run_rake_with_proto("schema_artifacts:dump")
            }.to change { read_proto_field_numbers }
              .from(nil)
              .to(a_string_starting_with("# This file is part of your schema definition"))

            # The file is maintained alongside the schema definition, not in the schema artifacts directory.
            expect(read_artifact(PROTO_FIELD_NUMBERS_FILE)).to be_nil
            expect(parsed_proto_field_numbers).to eq({
              "enums" => {},
              "messages" => {
                "ElasticGraphEventEnvelope" => {"fields" => {"op" => 1, "id" => 2, "version" => 3, "latency_timestamps" => 4, "record_product" => 5}, "next_number" => 6},
                "Product" => {
                  "fields" => {
                    "id" => 1,
                    "name" => 2
                  },
                  "next_number" => 3
                }
              }
            })

            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "name", "String"
                t.field "id", "ID"
                t.index "products"
              end
            EOS

            run_rake_with_proto("schema_artifacts:dump")

            expect(read_artifact(PROTO_SCHEMA_FILE)).to include("string id = 1;", "string name = 2;")
          end
        end

        describe "schema_artifacts:check" do
          it "reports `#{PROTO_FIELD_NUMBERS_FILE}` until it has been dumped alongside the schema definition" do
            write_proto_schema(table_defs: <<~EOS)
              s.object_type "Product" do |t|
                t.field "id", "ID"
                t.index "products"
              end
            EOS

            # The leading space verifies the file is reported at the root (alongside the schema
            # definition) rather than nested in the schema artifacts directory.
            expect {
              run_rake_with_proto("schema_artifacts:check")
            }.to abort_with a_string_including(" #{PROTO_FIELD_NUMBERS_FILE} (file does not exist)")

            run_rake_with_proto("schema_artifacts:dump")

            expect(run_rake_with_proto("schema_artifacts:check")).to include(PROTO_FIELD_NUMBERS_FILE, "up to date")
          end
        end

        private

        def write_proto_schema(table_defs:)
          ::File.write("schema.rb", <<~EOS)
            ElasticGraph.define_schema do |s|
              #{table_defs}
            end
          EOS
        end

        def run_rake_with_proto(*args)
          run_rake(*args) do |output|
            ElasticGraph::SchemaDefinition::RakeTasks.new(
              schema_element_name_form: :snake_case,
              index_document_sizes: false,
              path_to_schema: "schema.rb",
              schema_artifacts_directory: "config/schema/artifacts",
              extension_modules: [SchemaDefinition::APIExtension],
              output: output
            )
          end
        end

        def read_artifact(name)
          path = File.join("config", "schema", "artifacts", name)
          File.read(path) if File.exist?(path)
        end

        # The field-numbers file is dumped as a sibling of `path_to_schema` (`schema.rb`, above).
        def read_proto_field_numbers
          File.read(PROTO_FIELD_NUMBERS_FILE) if File.exist?(PROTO_FIELD_NUMBERS_FILE)
        end

        def parsed_proto_field_numbers
          ::YAML.safe_load(read_proto_field_numbers)
        end
      end
    end
  end
end
