module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaElements
        module ObjectInterfaceAndUnionExtension : ::ElasticGraph::SchemaDefinition::SchemaElements::ObjectType
          @proto_name: ::String?

          def proto_name: () -> ::String
          def to_proto: (Schema) -> ::String
          def proto_definition_kind: () -> :message
          def referenced_proto_types: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaElements::graphQLType]

          private

          def render_proto_message: (Schema, ::String message_name) -> ::String
          def render_proto_oneof: (Schema, ::String message_name) -> ::String
          def proto_fields: () -> ::Array[[
            ::ElasticGraph::SchemaDefinition::SchemaElements::Field,
            ::ElasticGraph::SchemaDefinition::Indexing::Field
          ]]
          def proto_field_type_for: (
            ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference,
            context_field_name: ::String
          ) -> [bool, ::String]
          def list_depth_and_base_type: (
            ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference
          ) -> [::Integer, ::ElasticGraph::SchemaDefinition::SchemaElements::TypeReference]
        end
      end
    end
  end
end
