module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      module SchemaElements
        module ScalarTypeExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType
          attr_reader protobuf_type: ::String?

          def protobuf: (type: ::String) -> void
          def finalize_protobuf_configuration!: () -> void
          def proto_name: () -> ::String
          def to_proto: () -> nil
          def proto_definition_priority: () -> 2
          def referenced_proto_types: () -> ::Array[::ElasticGraph::SchemaDefinition::SchemaElements::graphQLType]
        end
      end
    end
  end
end
