contact_links:
    - name: ❓ Questions and Help 🤔
      url: https://discord.gg/block-opensource
      about: This issue tracker is not for support questions. For support questions, please join the `#elasticgraph` channel on the Block Open Source Discord server.
