module ElasticGraph
  class GraphQL
    module Filtering
      class RangeQuerySupertype
        attr_reader field_name: ::String
        attr_reader operator: ::Symbol
        attr_reader value: untyped

        def initialize: (::String, ::Symbol, untyped) -> void

        def with: (
          ?field_name: ::String,
          ?operator: ::Symbol,
          ?value: untyped
        ) -> RangeQuery
      end

      class RangeQuery < RangeQuerySupertype
        UPPER_BOUND_OPERATORS: ::Array[::Symbol]
        LOWER_BOUND_OPERATORS: ::Array[::Symbol]

        def merge_into: (stringOrSymbolHash) -> void

        private

        def has_conflicting_operator?: (::Array[::Symbol] existing_operators) -> bool
      end
    end
  end
end
