module ElasticGraph
  class GraphQL
    module Filtering
      class RangeQuerySupertype
        attr_reader field_name: ::String
        attr_reader operator: ::Symbol
        attr_reader value: untyped

        def initialize: (::String, ::Symbol, untyped) -> void

        def with: (
          ?field_name: ::String,
          ?operator: ::Symbol,
          ?value: untyped
        ) -> RangeQuery
      end

      class RangeQuery < RangeQuerySupertype
        SAME_TYPE_OPS: ::Hash[::Symbol, ::Array[::Symbol]]

        def merge_into: (stringOrSymbolHash) -> void

        private

        def merge_operators: (::Hash[::Symbol, untyped]) -> ::Hash[::Symbol, untyped]

        def stricter_operator: (::Symbol, untyped, ::Symbol, untyped) -> [::Symbol, untyped]
      end
    end
  end
end
