module ElasticGraph
  class Admin
    module IndexDefinitionConfigurator
      module MappingUpdate
        EMPTY_PROPERTIES: ::Hash[::String, untyped]

        def self.build_mapping_update: (desired: ::Hash[::String, untyped], current: ::Hash[::String, untyped]) -> ::Hash[::String, untyped]
      end
    end
  end
end
