module ElasticGraph
  module SchemaDefinition
    module Indexing
      module FieldType
        class ObjectSuperType
          attr_reader schema_def_state: State
          attr_reader type_name: ::String
          attr_reader subfields: ::Array[Field]
          attr_reader mapping_options: Mixins::HasTypeInfo::optionsHash

          def initialize: (
            schema_def_state: State,
            type_name: ::String,
            subfields: ::Array[Field],
            mapping_options: Mixins::HasTypeInfo::optionsHash
          ) -> void

          def with: (
            ?schema_def_state: State,
            ?type_name: ::String,
            ?subfields: ::Array[Field],
            ?mapping_options: Mixins::HasTypeInfo::optionsHash
          ) -> Object
        end

        class Object < ObjectSuperType
          include _FieldType
          include Support::_MemoizableDataClass

          @to_mapping: ::Hash[::String, untyped]?
        end
      end
    end
  end
end
