module ElasticGraph
  module SchemaDefinition
    module Indexing
      module FieldType
        class Union
          include _FieldType

          attr_reader subtypes_by_name: ::Hash[::String, Object]
          def initialize: (::Hash[::String, Object]) -> void
        end
      end
    end
  end
end
