module ElasticGraph
  class Indexer
    type event = ::Hash[::String, untyped]

    module Operation
      class FactorySupertype
        attr_reader schema_artifacts: schemaArtifacts
        attr_reader index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]]
        attr_reader ingestion_adapters: ::Array[IngestionAdapter::_Adapter]
        attr_reader logger: ::Logger
        attr_reader skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]

        def initialize: (
          schema_artifacts: schemaArtifacts,
          index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]],
          ingestion_adapters: ::Array[IngestionAdapter::_Adapter],
          logger: ::Logger,
          skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]
        ) -> void

        def with: (
          ?schema_artifacts: schemaArtifacts,
          ?index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]],
          ?ingestion_adapters: ::Array[IngestionAdapter::_Adapter],
          ?logger: ::Logger,
          ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]
        ) -> instance
      end

      class Factory < FactorySupertype
        def build: (event) -> BuildResult

        private

        def ingestion_adapter_for: (event) -> IngestionAdapter::_Adapter?
        def prepare_event: (event) -> event
        def build_failed_result: (event, ::String, ::String) -> BuildResult
        def build_all_operations_for: (event, _RecordPreparer) -> ::Array[_Operation]
        def index_definitions_for: (::String) -> ::Array[DatastoreCore::_IndexDefinition]
        def raise: (*untyped) -> void

        class BuildResult
          attr_reader operations: ::Array[_Operation]
          attr_reader failed_event_error: FailedEventError?

          def initialize: (::Array[_Operation], FailedEventError?) -> void

          def with: (
            ?operations: ::Array[_Operation],
            ?failed_event_error: FailedEventError?
          ) -> BuildResult

          def self.success: (::Array[_Operation]) -> BuildResult
          def self.failure: (FailedEventError) -> BuildResult
        end
      end
    end
  end
end
