module ElasticGraph
  class Indexer
    type event = ::Hash[::String, untyped]

    module Operation
      class FactorySupertype
        attr_reader schema_artifacts: schemaArtifacts
        attr_reader index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]]
        attr_reader ingestion_adapters: ::Array[IngestionAdapter::_Adapter]
        attr_reader logger: ::Logger
        attr_reader skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]
        attr_reader skip_record_validation_percents_by_type: ::Hash[::String, ::Float]

        def initialize: (
          schema_artifacts: schemaArtifacts,
          index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]],
          ingestion_adapters: ::Array[IngestionAdapter::_Adapter],
          logger: ::Logger,
          skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
          skip_record_validation_percents_by_type: ::Hash[::String, ::Float]
        ) -> void

        def with: (
          ?schema_artifacts: schemaArtifacts,
          ?index_definitions_by_graphql_type: ::Hash[::String, ::Array[DatastoreCore::_IndexDefinition]],
          ?ingestion_adapters: ::Array[IngestionAdapter::_Adapter],
          ?logger: ::Logger,
          ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
          ?skip_record_validation_percents_by_type: ::Hash[::String, ::Float]
        ) -> instance
      end

      class Factory < FactorySupertype
        def build: (event) -> BuildResult

        private

        def ingestion_adapter_for: (event) -> IngestionAdapter::_Adapter?
        def prepare_event: (event) -> event
        def build_success_result: (event, _RecordPreparer, type_with_skipped_validation: ::String?) -> BuildResult
        def build_success_result_isolating_malformed_records: (event, _RecordPreparer, IngestionAdapter::_Adapter) -> BuildResult
        CRC32_SPACE_PER_PERCENT: ::Float
        def skip_validation?: (::String, event) -> bool
        def build_failed_result: (event, ::String, ::String) -> BuildResult
        def build_all_operations_for: (event, _RecordPreparer) -> ::Array[operation]
        def index_definitions_for: (::String) -> ::Array[DatastoreCore::_IndexDefinition]
        def raise: (*untyped) -> void

        class BuildResult
          attr_reader operations: ::Array[operation]
          attr_reader failed_event_error: FailedEventError?
          attr_reader type_with_skipped_validation: ::String?

          def initialize: (::Array[operation], FailedEventError?, ::String?) -> void

          def with: (
            ?operations: ::Array[operation],
            ?failed_event_error: FailedEventError?,
            ?type_with_skipped_validation: ::String?
          ) -> BuildResult

          def self.success: (::Array[operation], ?type_with_skipped_validation: ::String?) -> BuildResult
          def self.failure: (FailedEventError) -> BuildResult
        end
      end
    end
  end
end
