# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

ElasticGraph.define_schema do |schema|
  schema.json_schema_version 1
  schema.enforce_json_schema_version false

  # :snippet-start: on_each_generated_schema_element
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.object_type "Transaction" do |t|
    t.field "id", "ID"
    t.field "currency", "String" do |f|
      f.on_each_generated_schema_element do |element|
        element.directive "deprecated"
      end
    end
  end
  # :snippet-end:

  # :snippet-start: customize_derived_types_all
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.object_type "Campaign" do |t|
    t.field "id", "ID"
    t.customize_derived_types :all do |dt|
      dt.directive "deprecated"
    end
  end
  # :snippet-end:

  # :snippet-start: customize_derived_types_named
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.object_type "Order" do |t|
    t.field "id", "ID"
    t.customize_derived_types "OrderFilterInput", "OrderGroupedBy" do |dt|
      dt.directive "deprecated"
    end
  end
  # :snippet-end:

  # :snippet-start: customize_derived_type_fields
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.object_type "Product" do |t|
    t.field "id", "ID"
    t.customize_derived_type_fields "ProductConnection", "pageInfo", "totalEdgeCount" do |f|
      f.directive "deprecated"
    end
    t.index "products"
  end
  # :snippet-end:

  # :snippet-start: on_built_in_types
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.on_built_in_types do |type|
    type.append_to_documentation "This is a built-in ElasticGraph type."
  end
  # :snippet-end:

  # :snippet-start: on_root_query_type
  # Within `ElasticGraph.define_schema { ... }` in your schema definition:
  schema.on_root_query_type do |t|
    t.append_to_documentation "Generated by ElasticGraph."
  end
  # :snippet-end:
end
