# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

require "elastic_graph/constants"
require "elastic_graph/errors"
require "elastic_graph/support/memoizable_data"

module ElasticGraph
  module JSONIngestion
    module Artifacts
      # Exposes the current JSON schema generated by an in-memory schema definition.
      # @!attribute [r] results
      #   @return [ElasticGraph::SchemaDefinition::Results] results with JSON generation enabled
      # @!method initialize(results)
      #   @param results [ElasticGraph::SchemaDefinition::Results] results with JSON generation enabled
      #   @return [void]
      class FromSchemaDefinition < Support::MemoizableData.define(:results)
        # @param version [Integer] desired JSON schema version
        # @return [Hash<String, Object>] the JSON schema for the requested version, if available
        # @raise [Errors::MissingSchemaArtifactError] if the requested JSON schema version is not available
        def json_schemas_for(version)
          unless available_json_schema_versions.include?(version)
            raise Errors::MissingSchemaArtifactError, "The requested json schema version (#{version}) is not available. Available versions: #{available_json_schema_versions.to_a.join(", ")}."
          end

          @latest_versioned_json_schema ||= results.merge_field_metadata_into_json_schema(results.current_public_json_schema).json_schema
        end

        # @return [Set<Integer>] set of available JSON schema versions
        def available_json_schema_versions
          @available_json_schema_versions ||= Set[latest_json_schema_version]
        end

        # @return [Integer] the current JSON schema version
        def latest_json_schema_version
          results.current_public_json_schema[JSON_SCHEMA_VERSION_KEY]
        end
      end
    end
  end
end
