module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module SchemaElements
        module FieldExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::Field
          @json_schema_options: ::Hash[::Symbol, untyped]
          @non_nullable_in_json_schema: bool

          def json_schema_options: () -> ::Hash[::Symbol, untyped]
          def non_nullable_in_json_schema?: () -> bool
          def json_schema: (?nullable: bool?, **untyped) -> void
          def to_indexing_field_reference: () -> Indexing::FieldReference?
        end
      end
    end
  end
end
