module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module SchemaElements
        module ScalarTypeExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType
          BUILT_IN_SCALAR_JSON_SCHEMA_OPTIONS_BY_NAME: ::Hash[::String, ::Hash[::Symbol, untyped]]

          include HasJSONSchema

          def initialize_json_schema_extension: () { () -> void } -> void

          private

          def inferred_grouping_missing_value_placeholder: () -> ::String?
        end
      end
    end
  end
end
