module ElasticGraph
  module JSONIngestion
    module SchemaDefinition
      module SchemaElements
        module ScalarTypeExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::ScalarType
          @json_schema_options: ::Hash[::Symbol, untyped]

          def json_schema_options: () -> ::Hash[::Symbol, untyped]
          def json_schema: (**untyped) -> void
          def to_indexing_field_type: () -> Indexing::FieldType::Scalar
          def validate_json_schema_configuration!: () -> void

          private

          def inferred_grouping_missing_value_placeholder: () -> ::String?
        end
      end
    end
  end
end
