module ElasticGraph
  module SchemaDefinition
    module Mixins
      module ImplementsInterfaces: SchemaElements::TypeWithSubfields
        def implements: (*::String) -> void
        attr_reader implemented_interfaces: ::Array[SchemaElements::TypeReference]
        def verify_graphql_correctness!: () -> void
        def recursively_resolve_supertypes: () -> ::Set[abstractType]

        private

        def recursively_resolve_interface_supertypes: (?ancestors: ::Set[abstractType]) -> ::Array[abstractType]
      end
    end
  end
end
