module ElasticGraph
  module SchemaDefinition
    module Mixins
      module SupportsDefaultValue
        @default_value: untyped
        def default: (untyped) -> void
        def default_value_sdl: () -> ::String?
      end
    end
  end
end
