module ElasticGraph
  module Proto
    module SchemaDefinition
      module EnumTypeExtension: ::ElasticGraph::SchemaDefinition::SchemaElements::EnumType
        def to_proto_field_type: () -> ::String
      end
    end
  end
end
