module ElasticGraph
  module JSONIngestion
    class Indexer
      extend _BuildableFromParsedYaml[Indexer]
      extend Support::FromYamlFile[Indexer]

      attr_reader indexer: ::ElasticGraph::Indexer

      def initialize: (::ElasticGraph::Indexer) -> void

      def config: () -> ::ElasticGraph::Indexer::Config
      def datastore_core: () -> DatastoreCore
      def logger: () -> ::Logger
      def processor: () -> ::ElasticGraph::Indexer::Processor
      def schema_artifacts: () -> schemaArtifacts

      def process: (::String, ?refresh_indices: bool) -> void
      def process_returning_failures: (::String, ?refresh_indices: bool) -> ::Array[::ElasticGraph::Indexer::FailedEventError]
      def decode: (::String) -> ::Array[::Hash[::String, untyped]]
    end
  end
end
