module ElasticGraph
  module JSONIngestion
    class Indexer
      extend _BuildableFromParsedYaml[Indexer]
      extend Support::FromYamlFile[Indexer]

      attr_reader indexer: ::ElasticGraph::Indexer

      def initialize: (::ElasticGraph::Indexer) -> void

      def logger: () -> ::Logger
      def processor: () -> ::ElasticGraph::Indexer::Processor

      def process: (::String, ?refresh_indices: bool) -> void
      def process_returning_failures: (::String, ?refresh_indices: bool) -> ::Array[::ElasticGraph::Indexer::_IndexingFailure]
      def process_decoded_returning_failures: (::Array[IngestionAdapter::decodedEvent], ?refresh_indices: bool) -> ::Array[::ElasticGraph::Indexer::_IndexingFailure]
      def decode: (::String) -> ::Array[IngestionAdapter::decodedEvent]

      private

      def ingestion_adapter: () -> IngestionAdapter
    end
  end
end
