module ElasticGraph
  module JSONIngestion
    class IngestionAdapter
      include ::ElasticGraph::Indexer::IngestionAdapter::_Adapter

      type decodedEvent = ::Hash[::String, untyped]
      type jsonEvent = ::ElasticGraph::Indexer::Event[decodedEvent]

      ValidationResult: singleton(::ElasticGraph::Indexer::IngestionAdapter::ValidationResult)

      def initialize: (
        schema_artifacts: schemaArtifacts,
        logger: ::Logger,
        ?configure_record_validator: (^(Support::JSONSchema::ValidatorFactory) -> Support::JSONSchema::ValidatorFactory)?
      ) -> void

      @schema_artifacts: schemaArtifacts
      @logger: ::Logger
      @configure_record_validator: (^(Support::JSONSchema::ValidatorFactory) -> Support::JSONSchema::ValidatorFactory)?
      @record_preparer_factory: RecordPreparerFactory

      def events_from: (::Array[decodedEvent]) -> [::Array[jsonEvent], ::Array[::ElasticGraph::Indexer::MalformedEventError]]

      private

      def event_from: (decodedEvent) -> jsonEvent
      def envelope_failure_for: (decodedEvent) -> ::ElasticGraph::Indexer::MalformedEventError?
      def malformed: (decodedEvent, validation_target: ::String, message: ::String) -> ::ElasticGraph::Indexer::MalformedEventError
      def event_id_for: (decodedEvent) -> ::String
      def closest_available_json_schema_version: (::Integer) -> ::Integer?
      def validator: (::String, ::Integer) -> Support::JSONSchema::Validator

      @validator_factories_by_version: ::Hash[::Integer, Support::JSONSchema::ValidatorFactory]?
      def validator_factories_by_version: () -> ::Hash[::Integer, Support::JSONSchema::ValidatorFactory]

      def raise: (*untyped) -> bot
    end
  end
end
