module ElasticGraph
  module JSONIngestion
    class IngestionAdapter
      include ::ElasticGraph::Indexer::IngestionAdapter::_Adapter

      ValidationResult: singleton(::ElasticGraph::Indexer::IngestionAdapter::ValidationResult)

      attr_reader envelope_validator: EnvelopeValidator

      def initialize: (
        schema_artifacts: schemaArtifacts,
        logger: ::Logger,
        ?configure_record_validator: (^(Support::JSONSchema::ValidatorFactory) -> Support::JSONSchema::ValidatorFactory)?
      ) -> void

      @record_preparer_factory: RecordPreparerFactory

      private

      def raise: (*untyped) -> bot
    end
  end
end
