# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

source "https://rubygems.org"

gem "gem-release", "~> 2.2"
gem "irb", "~> 1.16" # Needed for yard on Ruby 4.0
gem "json_schemer", "~> 2.5"
gem "nokogiri", "~> 1.19"
gem "rake", "~> 13.3"
gem "redcarpet", "~> 3.6", ">= 3.6.1"
gem "yard", "~> 0.9"
gem "yard-markdown", "~> 0.5"
