ruby "3.2.5"

# Gem details for the elasticgraph gems. We're using the released versions.
elasticgraph_details = ["0.19.0.0"]

gem "elasticgraph-admin_lambda", *elasticgraph_details
# gem "elasticgraph-apollo", *elasticgraph_details
gem "elasticgraph-graphql_lambda", *elasticgraph_details
gem "elasticgraph-health_check", *elasticgraph_details
gem "elasticgraph-indexer_autoscaler_lambda", *elasticgraph_details
gem "elasticgraph-indexer_lambda", *elasticgraph_details
gem "elasticgraph-local", *elasticgraph_details
gem "elasticgraph-opensearch", *elasticgraph_details
gem "elasticgraph-query_interceptor", *elasticgraph_details
gem "elasticgraph-support", *elasticgraph_details

# elasticgraph-query_registry is an optional extension. Feel free to remove from here if you don't want to use it.
gem "elasticgraph-query_registry", *elasticgraph_details

gem "httpx", "~> 1.3"

group :development do
  gem "aws-sdk-sqs" # to allow publishing of fake data to staging. Remove when you no longer need that functionality.
  gem "byebug"
  gem "factory_bot"
  gem "faker"
  gem "rspec"
  gem "standard", "~> 1.40"
end
