module ElasticGraph
  module ProtoIngestion
    module IndexerExtension : ::ElasticGraph::Indexer
      @proto_ingestion_adapters: Array[Indexer::IngestionAdapter::_Adapter]?
      def ingestion_adapters: () -> Array[Indexer::IngestionAdapter::_Adapter]
    end
  end
end
