module ElasticGraph
  module SchemaDefinition
    module Indexing
      class FieldSupertype
        attr_reader name: ::String
        attr_reader name_in_index: ::String
        attr_reader type: SchemaElements::TypeReference
        attr_reader indexing_field_type: _FieldType
        attr_reader accuracy_confidence: Field::accuracyConfidence
        attr_reader mapping_customizations: ::Hash[::Symbol, untyped]
        attr_reader source: SchemaElements::FieldSource?
        attr_accessor runtime_field_script: ::String?
        attr_reader doc_comment: ::String?

        def initialize: (
          name: ::String,
          name_in_index: ::String,
          type: SchemaElements::TypeReference,
          indexing_field_type: _FieldType,
          accuracy_confidence: Field::accuracyConfidence,
          mapping_customizations: ::Hash[::Symbol, untyped],
          source: SchemaElements::FieldSource?,
          runtime_field_script: ::String?,
          doc_comment: ::String?
        ) -> Field

        def with: (
          ?name: ::String,
          ?name_in_index: ::String,
          ?type: SchemaElements::TypeReference,
          ?indexing_field_type: _FieldType,
          ?accuracy_confidence: Field::accuracyConfidence,
          ?mapping_customizations: ::Hash[::Symbol, untyped],
          ?source: SchemaElements::FieldSource?,
          ?runtime_field_script: ::String?,
          ?doc_comment: ::String?
        ) -> Field
      end

      class Field < FieldSupertype
        type accuracyConfidence = SchemaElements::Field::accuracyConfidence
        @mapping: ::Hash[::String, untyped]?
        def mapping: () -> ::Hash[::String, untyped]

        def self.normalized_mapping_hash_for: (::Array[Field]) -> ::Hash[::String, untyped]
      end
    end
  end
end
