module ElasticGraph
  module SchemaDefinition
    module Indexing
      class SourcedFromUpdateTargetsResolver
        @schema_def_state: State

        def initialize: (State) -> void
        def resolve: () -> ::Hash[::String, ::Array[SchemaArtifacts::RuntimeMetadata::UpdateTarget]]

        private

        @relationship_chain_resolver: RelationshipChainResolver

        def resolve_for_type: (indexableType) { (::Symbol, ::String) -> void } -> ::Array[[::String, SchemaArtifacts::RuntimeMetadata::UpdateTarget]]
        def resolve_top_level_update_targets: (indexableType) { (::Symbol, ::String) -> void } -> ::Array[[::String, SchemaArtifacts::RuntimeMetadata::UpdateTarget]]
        def resolve_nested_update_targets: (indexableType) { (::Symbol, ::String) -> void } -> ::Array[[::String, SchemaArtifacts::RuntimeMetadata::UpdateTarget]]
        def resolve_top_level_update_target: (indexableType, ResolvedRelationship, ::Array[SchemaElements::Field]) { (::Symbol, ::String) -> void } -> [::String, SchemaArtifacts::RuntimeMetadata::UpdateTarget]?
        def group_sourced_fields_by_relationship_name: (indexableType) -> ::Hash[::String, ::Array[SchemaElements::Field]]
        def resolve_sourced_fields_and_chains: (indexableType) { (::Symbol, ::String) -> void } -> ::Array[[::Array[SchemaElements::Field], ResolvedRelationshipChain]]
        def relationship_chain_resolver: () -> RelationshipChainResolver
        def resolve_nested_update_target: (indexableType, ::Array[SchemaElements::Field], ResolvedRelationshipChain) { (::Symbol, ::String) -> void } -> [::String, SchemaArtifacts::RuntimeMetadata::UpdateTarget]?
        def raise_if_errors: (::Array[::String], ::Array[::String]) -> void
      end
    end
  end
end
