module ElasticGraph
  module SchemaDefinition
    module Indexing
      interface _SourcedFieldParamsHost
        def object_type: () -> indexableType
        def related_type: () -> indexableType
        def sourced_fields: () -> ::Array[SchemaElements::Field]
        def field_path_resolver: () -> SchemaElements::FieldPath::Resolver
      end

      module SourcedFieldParamsResolver : _SourcedFieldParamsHost
        def resolve_sourced_field_params: () -> [
          ::Hash[::String, SchemaArtifacts::RuntimeMetadata::DynamicParam],
          ::Array[::String]
        ]
      end
    end
  end
end
