#!/usr/bin/env bash

# Capture part number before `source` potentially alters positional params.
part=${3:-}

source "script/ci_parts/setup_env" "test" $1 $2

# We don't want to bother checking coverage on JRuby, for a few reasons:
# - The Ruby coverage APIs don't fully work on JRuby.
# - It slows things down.
# - We've chosen to annotate files with `# :nocov:` from an MRI perspective. Lines of code which are run on MRI but not JRuby don't have `# :nocov:
unset COVERAGE

# On CI, this is quite slow, and when we use the progress formatter the CI build can appear to get stuck
# because 20+ minutes may pass before the line of progress dots completes, and GitHub actions streams build
# output line-by-line. We use the documentation formatter here so that the output has many lines and there's
# more obviously ongoing progress on CI.
rspec_format="--format documentation"

run_gems() {
  local spec_dirs=""
  for gem in "$@"; do
    if [ -d "$gem/spec" ]; then
      spec_dirs="$spec_dirs $gem/spec"
    fi
  done
  if [ -n "$spec_dirs" ]; then
    script/flatware_rspec $spec_dirs $rspec_format
  fi
}

run_gems_with_datastore_halted() {
  halt_datastore_daemon
  run_gems $gems_to_build_with_datastore_halted
}

case "$part" in
  1)
    # graphql excluding acceptance (~19m); acceptance specs split to part 3.
    script/flatware_rspec elasticgraph-graphql/spec $rspec_format --tag ~type:acceptance
    ;;
  2)
    run_gems elasticgraph-schema_definition elasticgraph-indexer
    ;;
  3)
    # The two slowest individual spec groups: graphql acceptance (~8m) and
    # elasticgraph-local (~6m, requires halted datastore).
    script/flatware_rspec elasticgraph-graphql/spec $rspec_format --tag type:acceptance
    run_gems_with_datastore_halted
    ;;
  4)
    # All remaining gems not covered by parts 1-3.
    remaining=$(echo $gems_to_build_with_datastore_booted | tr ' ' '\n' | grep -v -E "^(elasticgraph-graphql|elasticgraph-schema_definition|elasticgraph-indexer)$" | tr '\n' ' ')
    run_gems $remaining
    ;;
  *)
    # Default: run everything (backward-compatible with no part argument).
    script/run_specs $rspec_format
    run_gems_with_datastore_halted
    ;;
esac
