# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

require "elastic_graph/schema_definition/schema_artifact_manager"
require "stringio"

module ElasticGraph
  module SchemaDefinition
    RSpec.describe SchemaArtifact, :in_temp_dir do
      it "renders the comment preamble using the configured comment prefix so artifacts can use their format's comment syntax" do
        artifact = SchemaArtifact.new(
          "widgets.proto",
          "message Widget {}",
          :itself.to_proc,
          :itself.to_proc,
          [],
          "//"
        )

        artifact.dump(::StringIO.new)

        expect(::File.read("widgets.proto")).to eq(<<~EOS.strip)
          // Generated by `bundle exec rake schema_artifacts:dump`.
          // DO NOT EDIT BY HAND. Any edits will be lost the next time the rake task is run.
          message Widget {}
        EOS
      end
    end
  end
end
