module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      class FieldNumberMappings
        type fieldNumbersByName = ::Hash[::String, ::Integer]

        MAX_FIELD_NUMBER: ::Integer
        RESERVED_FIELD_NUMBER_RANGE: ::Range[::Integer]
        MAX_ENUM_VALUE_NUMBER: ::Integer

        @field_numbers_by_message: ::Hash[::String, fieldNumbersByName]
        @value_numbers_by_enum: ::Hash[::String, ::Hash[::String, ::Integer]]
        @used_field_numbers_by_message: ::Hash[::String, ::Set[::Integer]]
        @used_enum_value_numbers_by_enum: ::Hash[::String, ::Set[::Integer]]

        def self.from_artifact: (untyped) -> instance
        def self.parse_messages: (untyped) -> ::Hash[::String, fieldNumbersByName]
        def self.parse_enums: (untyped) -> ::Hash[::String, ::Hash[::String, ::Integer]]
        def self.validated_field_number: (::String, ::String, untyped) -> ::Integer
        def self.verify_no_number_collisions: (::Hash[::String, ::Integer], ::String) -> void
        def self.verify_known_keys: (::Hash[untyped, untyped], ::Array[::String], ::String) -> void

        def initialize: (
          field_numbers_by_message: ::Hash[::String, fieldNumbersByName],
          value_numbers_by_enum: ::Hash[::String, ::Hash[::String, ::Integer]]
        ) -> void

        def field_number_for: (
          message_name: ::String,
          public_field_name: ::String,
          previous_field_names: ::Array[::String]
        ) -> ::Integer
        def enum_value_numbers_for: (::String, ::Array[::String]) -> ::Hash[::String, ::Integer]
        def to_artifact: () -> ::Hash[::String, untyped]

        private

        def used_field_numbers_for: (::String, fieldNumbersByName) -> ::Set[::Integer]
        def used_enum_value_numbers_for: (::String, ::Hash[::String, ::Integer]) -> ::Set[::Integer]
        def allocate_field_number: (::Set[::Integer]) -> ::Integer
        def allocate_enum_value_number: (::Set[::Integer]) -> ::Integer
        def migrate_renamed_field_number: (fieldNumbersByName, ::Array[::String]) -> ::Integer?
      end
    end
  end
end
