module ElasticGraph
  module ProtoIngestion
    module SchemaDefinition
      class Identifier
        VALID_IDENTIFIER: ::Regexp

        def self.validate_package_name: (::String) -> ::String
      end
    end
  end
end
