# Copyright 2024 - 2026 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

require "elastic_graph/local/rake_tasks"

ElasticGraph::Local::RakeTasks.new(
  local_config_yaml: File.expand_path("local_settings.yaml", __dir__),
  path_to_schema: File.expand_path("schema.rb", __dir__)
) do |tasks|
  tasks.opensearch_versions = []
  tasks.enforce_json_schema_version = false

  # :snippet-start: schema_element_name_form
  # Within `ElasticGraph::Local::RakeTasks.new { ... }` in your `Rakefile`:
  tasks.schema_element_name_form = :snake_case
  # :snippet-end:

  # :snippet-start: schema_element_name_overrides
  # Within `ElasticGraph::Local::RakeTasks.new { ... }` in your `Rakefile`:
  tasks.schema_element_name_overrides = {
    gt: "greaterThan",
    gte: "greaterThanOrEqualTo",
    lt: "lessThan",
    lte: "lessThanOrEqualTo"
  }
  # :snippet-end:

  # :snippet-start: derived_type_name_formats
  # Within `ElasticGraph::Local::RakeTasks.new { ... }` in your `Rakefile`:
  tasks.derived_type_name_formats = {FilterInput: "%{base}Filter"}
  # :snippet-end:

  # :snippet-start: type_name_overrides
  # Within `ElasticGraph::Local::RakeTasks.new { ... }` in your `Rakefile`:
  tasks.type_name_overrides = {JsonSafeLong: "BigInt"}
  # :snippet-end:
end
