# Put any custom Rubocop configuration here. Note, however, that standardrb (which wraps rubocop)
# does not allow its lint settings to be overriden--we can only add new cops here, so please confirm
# that any new cops added here are actually effective.

require:
  - ./custom_cops/documentation_cop

CustomCops/DocumentationCop:
  Enabled: true
  Exclude:
    # Each `Country` enum value doc string lacks a period, intentionally--they are just like `United States` or `Turkey`.
    - config/schema/country.rb
    # Each `Currency` enum value doc string lacks a period, intentionally--they are just like `United States Dollar` or `Mexican Peso`.
    - config/schema/currency.rb
