module ElasticGraph
  class GraphQL
    module Resolvers
      class GraphQLAdapter
        def initialize: (
          schema: Schema,
          query_adapter: Resolvers::QueryAdapter,
          runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema,
          resolvers: ::Array[Resolvers::_Resolver]
        ) -> void
      end
    end
  end
end
