module ElasticGraph
  class GraphQL
    module Resolvers
      class Hash
        include _Resolver

        @schema_element_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames

        def initialize: (
          schema_element_names: SchemaArtifacts::RuntimeMetadata::SchemaElementNames
        ) -> void
      end
    end
  end
end
