module ElasticGraph
  class GraphQL
    module Resolvers
      type fieldArgs = ::Hash[::Symbol, untyped]

      interface _Resolver
        def call: (
          Schema::Field,
          untyped,
          fieldArgs,
          ::GraphQL::Query::Context
        ) -> untyped
      end
    end
  end
end
