module ElasticGraph
  class GraphQL
    module Resolvers
      class ListRecords
        include _Resolver

        def initialize: (resolver_query_adapter: Resolvers::QueryAdapter) -> void
      end
    end
  end
end
