# This workflow doesn't have access to secrets and has a read-only token
# It exists to trigger `update-gem-version-artifacts.yaml` in a two-step process,
# as recommended by https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
name: Dependabot PR Check
on:
  pull_request

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
