name: Update Gem Version Artifacts

on:
  workflow_run:
    workflows: ["Dependabot Gem PR Check"]
    types:
      - completed

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'dependabot[bot]'
    # The 'permissions' here apply to the GITHUB_TOKEN, but we'll actually be pushing with the PAT
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Create GitHub Token
        id: create-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: block

      - name: Checkout Git Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          # Use the PAT for checkout to ensure proper permissions
          token: ${{ steps.create-token.outputs.token }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "4.0"
          bundler-cache: true
          cache-version: 2

      - name: Update RBS collection
        run: bundle exec rbs collection update

      - name: Update gem version constraints
        run: |
          bundle config --local deployment false
          script/update_gem_constraints

      - name: Commit and push if changed
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add rbs_collection.lock.yaml Gemfile Gemfile.lock *.gemspec
            git commit -m "Update gem version artifacts."

            # Push using the PAT
            git remote set-url origin "https://x-access-token:${{ steps.create-token.outputs.token }}@github.com/${{ github.repository }}.git"
            git push origin "HEAD:$HEAD_BRANCH"
          fi
