module ElasticGraph
  module Warehouse
    module SchemaDefinition
      module FactoryExtension: ::ElasticGraph::SchemaDefinition::Factory
        def new_results: () -> ::ElasticGraph::SchemaDefinition::Results
      end
    end
  end
end
