module ElasticGraph
  module Warehouse
    module SchemaDefinition
      module FactoryExtension: ::ElasticGraph::SchemaDefinition::Factory
        def new_field: (**untyped) ?{ (::ElasticGraph::SchemaDefinition::SchemaElements::Field) -> void } -> ::ElasticGraph::SchemaDefinition::SchemaElements::Field
      end
    end
  end
end
