module ElasticGraph
  module Warehouse
    module SchemaDefinition
      module ObjectInterfaceAndUnionExtension : _ObjectInterfaceAndUnionExtensionInterface
        EXCLUDED_FROM_WAREHOUSE: ::Symbol

        def warehouse_table: (::String) -> void
        def exclude_from_warehouse: () -> void
        def index: (::String name, **untyped settings) ?{ (untyped) -> void } -> void
        def to_warehouse_column_type: () -> ::String
        def warehouse_table_def: () -> (WarehouseTable | ::Symbol)?

        @warehouse_table_def: (WarehouseTable | ::Symbol)?
      end

      interface _ObjectInterfaceAndUnionExtensionInterface
        def schema_def_state: () -> untyped
        def indexing_fields_by_name_in_index: () -> ::Hash[::String, untyped]
      end
    end
  end
end
