module ElasticGraph
  module Warehouse
    module SchemaDefinition
      module ObjectInterfaceAndUnionExtension : _ObjectInterfaceAndUnionExtensionInterface
        def to_warehouse_column_type: () -> ::String
      end

      interface _ObjectInterfaceAndUnionExtensionInterface
        def indexing_fields_by_name_in_index: () -> ::Hash[::String, ::ElasticGraph::SchemaDefinition::SchemaElements::Field]
      end
    end
  end
end
