module ElasticGraph
  module Warehouse
    module SchemaDefinition
      class WarehouseTableSupertype
        attr_reader name: ::String
        attr_reader index: ::ElasticGraph::SchemaDefinition::Indexing::Index

        def initialize: (name: ::String, index: ::ElasticGraph::SchemaDefinition::Indexing::Index) -> void
      end

      class WarehouseTable < WarehouseTableSupertype
        def to_config: () -> ::Hash[::String, ::String]
        def table_schema: () -> ::String

        private

        def table_field: (::ElasticGraph::SchemaDefinition::Indexing::Field) -> ::String
      end
    end
  end
end
